export const actiontype = {
    REQUEST_LOGIN: 'REQUEST_LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',
    LOGOUT: 'LOGOUT',
    REQUEST_SINGUP: 'REQUEST_SINGUP',
    SINGUP_SUCCESS: 'SINGUP_SUCCESS',

}