export const actiontype = {
    REQUEST_LOGIN: 'REQUEST_LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',
    LOGOUT: 'LOGOUT',
    REQUEST_SIGNUP: 'REQUEST_SIGNUP',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',

}